language: ruby
rvm:
- 2.7.6
services:
  - mysql
branches:
  only:
    - master
    - /quarter\d*/
    - develop
    - /2.\d*.\d*/
env:
- TEST_SUITE=rspec RAILS_VERSION=4.1.9
script:
- bundle exec rake app:transam_accounting:prepare_rspec
- bundle exec $TEST_SUITE
before_script:
- bundle update transam_core transam_transit
- cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
before_install:
- mysql -e "create database IF NOT EXISTS transam_accounting_testing;" -uroot
- bundle config set without 'not_travis'
- gem install -v 2.3.4 bundler --document=

