language: ruby
rvm:
- 2.2.2
branches:
  only:
    - master
    - /quarter\d*/
env:
- TEST_SUITE=rspec RAILS_VERSION=4.1.9
script:
- bundle exec rake app:transam_accounting:prepare_rspec
- bundle exec $TEST_SUITE
before_script:
- bundle update transam_core transam_transit
- cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
before_install:
- mysql -e "create database IF NOT EXISTS transam_accounting_testing;" -uroot
bundler_args: --without not_travis
