language: ruby
rvm:
- 2.1.1
branches:
  only:
  - master
env:
- TEST_SUITE=rspec
script:
- bundle exec rake app:transam_accounting:prepare_rspec
- bundle exec $TEST_SUITE
before_install:
- openssl aes-256-cbc -K $encrypted_1dcbfc78be6f_key -iv $encrypted_1dcbfc78be6f_iv
  -in spec/dummy/db/schema.rb.enc -out spec/dummy/db/schema.rb -d
